_target_: src.baselines.backbone.anthropic_backbone.AnthropicBackbone
name: anthropic-claude-3-haiku
model_name: anthropic-claude-3-haiku
parameters:
  seed: 76097149
  temperature: 0
context_composer: ${context_composer}
